### ISSUE TITLE
Saving enrollment data to File

### ISSUE THREAD

**Issue by lmick** [takuya-takeuchi/WinBiometricDotNet#19]
Hello Takuya,

im trying to use the Windows Biometric Framework for internal use in an Application.
Is it somehow possible to save the enrollment data to a file without commiting it to the WinBioDatabase and to verify it by using the data in the file?
I cannot use the Fingerprint image, because the Fingerprint sensor im using does not support CaptureSample.

Thanks

**Comment by takuya-takeuchi** [comment]
@lmick Enrollment datum may be accessable via 
https://github.com/takuya-takeuchi/WinBiometricDotNet/blob/b6d19df940d179112d0dc2d55d648cbd663dade7/sources/WinBiometricDotNet/WinBiometric.cs#L2024

The above code function intents to regist database.
The database could be file.

However, I don't know whether finger image is in.
And even finger template may not exist.
So we may not have method adding image or template manually.

At least, I never hear wbf support sending file and verify it in device.

**Comment by lmick** [comment]
Thank you for the quick response.
I will try to use the info.
Thank you for making this Open Source.
